### ISSUE TITLE
Plugin doesn't save PDF on Windows installation

### ISSUE THREAD

**Issue by hfbauman** [PellelNitram/xournalpp_htr#7]
Hi! Love the work you've done so far and I'm very excited to try it out. I believe I installed everything correctly, including using a nightly build of Xournal++, but when I use the plugin it doesn't seem to do anything. If I haven't saved the document, it gives me an error, but other than that as soon as I hit save, the UI unfreezes, and no file is created. I've looked for logs to tell me what might be wrong, but I haven't been able to find them. What additional information can I provide to help debug this?

**Comment by PellelNitram** [comment]
Hi there @hfbauman,

thanks a lot for your issue and your kind words! Indeed, the installation process is very far from optimal currently with this statement holding even more so for Windows (because I cannot test it on Windows as I don't have access to it currently).

Thanks for giving Xournal++ HTR a try - I greatly appreciate your interest!

First of all, you need to save your document as a `xopp` file using the normal Xournal++ workflow because (for now) Xournal++ HTR only works on saved `xopp` files. Very good point that there are no logs written currently - I will add that as issue for easier debugging. On Linux, I start the nightly AppImage via commandline and there, I can see logs and the progress of the Xournal++ HTR plugin, see my attached screenshot:

![Screenshot from 2024-09-09 21-32-47](https://github.com/user-attachments/assets/46d1ae45-e2b7-4fea-827c-58e20b94e429)

Could you please try to open your Xournal++ nightly version via command-line and then paste a screenshot here of what it prints? I believe that debugging your setup would be quite simple once we have this screenshot. Is it maybe possible to use PowerShell to open the Xournal++ nightly via command-line?

While you try this, I will go back to coding and implement the logging feature that you suggested, thanks!

**Comment by hfbauman** [comment]
I've tried opening Xournal++ from the command line--I had to add the `.exe` location to the `PATH`. Unfortunately, it doesn't seem to do a blocking start, i.e. the command window immediately returns and doesn't display any output from Xournal++.  Do you have any other ideas?

I agree, once I can see logs or any output at all debugging should be much easier!

**Comment by PellelNitram** [comment]
OK, I understand.

Then let's go a slightly different route: The Lua plugin calls a certain Python script that does the actual work. We can call that Python script ourselves as well and that's what I propose to do next. This route does not fix the integration into Xournal++ but will guide us to understand if the underlying Python script workhorse does work indeed.

To guide my help, I will ask you a few questions next:

1. Have you installed the Python environment as explained in the README using `conda`? Has that worked? Can you successfully start the corresponding `conda` Python interpreter? If yes then proceed to next question and if no then please try to set up the `conda` environment first.
2. Please try to run the following command using the activated Python environment: `python xournalpp_htr/run_htr.py -if <path to your xopp file> -of output.pdf` with `<path ... file>` replaced correspondingly. What does it say?

**Comment by hfbauman** [comment]
I'm familiar with `conda`, so I think I have that set up properly. There's a small chance that I didn't install HTR_Pipeline such that it is discoverable, but I think I have it correct. Here's the output from running the python script in the environment:

![image](https://github.com/user-attachments/assets/691e6edd-6204-42c7-908b-4aed18980062)

**Comment by PellelNitram** [comment]
Great, thanks. The screenshot is very helpful!

It looks like you have installed the `conda` environment correctly - great!

I am also inclined to say that you probably installed `HTRPipeline` correctly - again great!

The error that we see indicates that `run_htr.py` is not able to save a temporary file it creates in the folder `C:\tmp`.

**Could you please create the folder `C:\tmp` and try to run the script again?** Thanks!

**Comment by hfbauman** [comment]
The python script works after adding `C:\tmp`! I would recommend adding something to the script to handle this case or adding documentation to the `README`.

Unfortunately, the behavior through Xournal++ when activating the plugin is still unchanged. What should I try next?

**Comment by PellelNitram** [comment]
Cool, it's great to hear of this first success!

> I would recommend adding something to the script to handle this case or adding documentation to the README.

Done. I have added a line in the code that automatically creates the temporary file's parent folder.

> Unfortunately, the behavior through Xournal++ when activating the plugin is still unchanged. What should I try next?

OK, let me think. First of all, the Python script worked now and I assume that the searchable output PDF file was created as expected - is this assumption correct?

If that assumption is correct, then the problem must come from the plugin itself. Luckily, it is probably not a difficult problem. Could you capture somehow what you see exactly when you press the "Xournal++ HTR" button in the plugin section of Xournal++? Maybe with a screen recording uploaded to imgur?

Also, I am happy to jump on a video call to solve the problem interactively in case you are up for that? In that case, we'd just try to solve the problem together interactively and I would add our findings (and hopefully solution) to this issue here afterwards.

Cheers!

**Comment by hfbauman** [comment]
Yes, the python script works as expected. I'm happy to talk synchronously--what's the best way to contact you directly to set that up?

**Comment by PellelNitram** [comment]
Great, thanks, that's awesome to hear! Please send me an email to s1691089@ed.ac.uk with a selection of dates and times that you'd be free to talk. Then, I can send you a video call link to solve the problem together.

**Comment by hfbauman** [comment]
@PellelNitram email sent!

**Comment by PellelNitram** [comment]
Just to report on the progress here: After a great video call session, @hfbauman and I identified two root problems:

1. First, the `config` file needed to be configured. There was no mention of it in the README.
2. Second, there was a bug in the `export_to_pdf_with_xournalpp` function where `xournalpp` is called to export the `xopp` file at hand to a PDF file. This step failed for filenames with spaces because of the lack of quotes.

The two problems have been fixed in PR #9 and #10 by @hfbauman - thanks for your support and the PRs! :-)

This issue is thereby solved.
